# Site settings
title: 4IZ268 – Webové technologie
email: jirka@kosek.cz
description: > # this means to ignore newlines until "baseurl:"
  Stránky s užitečnými informacemi pro studenty předmětu
  Webové technoligie (4IZ268) na VŠE Praha.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://4iz268.github.io" # the base hostname & protocol for your site
twitter_username: 4iz268
github_username:  4iz268
future: true

# Build settings
markdown: kramdown
